name: Run Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run the cron job
        run: curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "http://ososbus.rf.gd/os.php"
